export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const CONVERSION_EVENT = 'CONVERSION_EVENT';
export const ALL_CONVERSION_EVENTS = 'ALL_CONVERSION_EVENTS';
